"""add sr attachment path to jobs

Revision ID: 0b014ef379ee
Revises: 5b5c7852d903
Create Date: 2026-09-14 21:30:40.159764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b014ef379ee'
down_revision: Union[str, Sequence[str], None] = '5b5c7852d903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('sr_attachment_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'sr_attachment_path')
    # ### end Alembic commands ###
