"""store files in database instead of disk

Revision ID: 9370402274a8
Revises: 57c6cb28e586
Create Date: 2026-09-17 08:30:52.608379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9370402274a8'
down_revision: Union[str, Sequence[str], None] = '57c6cb28e586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing jobsheet rows point to files already lost to Render's ephemeral disk —
    # they're no longer usable, so we clear them before adding the new required columns.
    op.execute("DELETE FROM jobsheets")

    op.add_column('jobs', sa.Column('sr_attachment_filename', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('sr_attachment_content_type', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('sr_attachment_data', sa.LargeBinary(), nullable=True))
    op.drop_column('jobs', 'sr_attachment_path')
    op.add_column('jobsheets', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('jobsheets', sa.Column('content_type', sa.String(length=100), nullable=False))
    op.add_column('jobsheets', sa.Column('file_data', sa.LargeBinary(), nullable=False))
    op.drop_column('jobsheets', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobsheets', sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('jobsheets', 'file_data')
    op.drop_column('jobsheets', 'content_type')
    op.drop_column('jobsheets', 'filename')
    op.add_column('jobs', sa.Column('sr_attachment_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'sr_attachment_data')
    op.drop_column('jobs', 'sr_attachment_content_type')
    op.drop_column('jobs', 'sr_attachment_filename')
    # ### end Alembic commands ###